#soon ...
#sudo: false
dist: trusty
language: python
python:
    - "2.7"
env:
    - CKANVERSION=inventory
    - PGVERSION=9.6
install:
    - bash bin/travis-build.bash
    - pip install coveralls
script: sh bin/travis-run.sh
