version: 2
jobs:
  test_local_docker:
    working_directory: ~/ckanext-react_usmetadata
    machine: true
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
      - run:
          name: Start CKAN
          command: |
            docker-compose build
            docker-compose up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:5000/dataset -timeout 120s
      - run:
          name: Run ckanext-react_usmetadata Tests
          command: |
            docker-compose exec ckan /bin/bash -c "nosetests --ckan --with-pylons=src_extensions/react_usmetadata/docker_test.ini src_extensions/react_usmetadata/"
  build_ckan_28:
    working_directory: ~/ckanext-react_usmetadata
    machine:
      image: circleci/classic:201708-01
      # image: circleci/postgres:9.6-alpine
    environment:
      CKANVERSION=2.8
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh
  build_ckan_23:
    working_directory: ~/ckanext-react_usmetadata
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.3
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh

  build_gsa_ckan_inventory:
    working_directory: ~/ckanext-react_usmetadata
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=inventory
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh
  
  build_gsa_ckan_datagov:
    working_directory: ~/ckanext-react_usmetadata
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=datagov
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_local_docker
      - build_ckan_28
      - build_ckan_23
      - build_gsa_ckan_inventory
      - build_gsa_ckan_datagov
